require("config.theme")
require("config.bufferline")
require("config.firenvim")
require("config.lspkind")
require("config.neoformat")
require("config.nerdcommenter")
require("config.office")
require("config.telescope")
require("config.treesitter")
require("config.autopairs")

require("config.compe")

require("config.vsnip")

require("config.lualineNvim")
require("config.tree")
require("config.dashboard")
require("config.cmake")

require("config.doge")
require("config.vimspector")
require("config.godot")
require("config.easymotion")
require("config.vista")
