require("config.theme")
require("config.office")
require("config.firenvim")
require("config.treesitter")
require("config.neoformat")
require("config.nerdcommenter")
require("config.barbar")
require("config.telescope")
