vim.api.nvim_set_keymap("i", "<c-_>", "<ESC>:call nerdcommenter#Comment('n', 'toggle')<CR>i",           {noremap=true})
vim.api.nvim_set_keymap("n", "<c-_>", ":call nerdcommenter#Comment('', 'toggle')<CR>",                  {noremap=true})
vim.api.nvim_set_keymap("v", "<c-_>", ":call NERDComment('x', 'toggle')<CR>v",                          {noremap=true})
vim.api.nvim_set_keymap("i", "<space>c<space>", "<ESC>:call nerdcommenter#Comment('n', 'toggle')<CR>i", {noremap=true})
vim.api.nvim_set_keymap("n", "<space>c<space>", ":call nerdcommenter#Comment('', 'toggle')<CR>",        {noremap=true})
vim.api.nvim_set_keymap("v", "<space>c<space>", ":call NERDComment('x', 'toggle')<CR>v",                {noremap=true})
