vim.api.nvim_set_keymap(Keys.I, "<c-_>", "<ESC>:call nerdcommenter#Comment('n', 'toggle')<CR>i",           Keys.Noremap)
vim.api.nvim_set_keymap(Keys.N, "<c-_>", ":call nerdcommenter#Comment('', 'toggle')<CR>",                  Keys.Noremap)
vim.api.nvim_set_keymap(Keys.V, "<c-_>", ":call NERDComment('x', 'toggle')<CR>v",                          Keys.Noremap)
vim.api.nvim_set_keymap(Keys.I, "<space>c<space>", "<ESC>:call nerdcommenter#Comment('n', 'toggle')<CR>i", Keys.Noremap)
vim.api.nvim_set_keymap(Keys.N, "<space>c<space>", ":call nerdcommenter#Comment('', 'toggle')<CR>",        Keys.Noremap)
vim.api.nvim_set_keymap(Keys.V, "<space>c<space>", ":call NERDComment('x', 'toggle')<CR>v",                Keys.Noremap)
