[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
miette   = { version = "5.10.0", features = ["fancy"] }
mlua     = { version = "0.9.2", features  = ["luajit"] }
nvim-oxi = { version = "0.5.1", features = ["neovim-0-10", "mlua"] }
