vim.g.coc_global_extensions = {
    "coc-calc",
    "coc-clangd",
    "coc-cmake",
    "coc-css",
    "coc-cssmodules",
    "coc-dash-complete",
    "coc-dot-complete",
    "coc-emmet",
    "coc-eslint",
    "coc-explorer",
    "coc-flutter",
    "coc-gitignore",
    "coc-html",
    "coc-json",
    "coc-omnisharp",
    "coc-project",
    "coc-pydocstring",
    "coc-pyright",
    "coc-sh",
    "coc-snippets",
    "coc-svg",
    "coc-tailwindcss",
    "coc-tslint",
    "coc-tsserver",
    "coc-ultisnips",
    "coc-vetur",
    "coc-vimlsp",
    "coc-webpack",
    "coc-xml",
    "coc-yaml",
}

vim.g.coc_snippet_next = "<tab>"

vim.cmd "source $HOME/.config/nvim/vimscript/plugins/coc.vim"
