name: Rust

on:
  push:
    tags:
      - "v*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd rust && sudo apt install luajit pkg-config libluajit-5.1-2 libluajit-5.1-common libluajit-5.1-dev && cargo build --verbose --release && cd ..
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: "target/release/librust.so"
